// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Groviera")>]
[<assembly: AssemblyProductAttribute("Taipan")>]
[<assembly: AssemblyCompanyAttribute("Enkomio")>]
[<assembly: AssemblyDescriptionAttribute("A web application vulnerability assessment tool.")>]
[<assembly: AssemblyVersionAttribute("1.2.1202831766")>]
[<assembly: AssemblyFileVersionAttribute("1.2.1202831766")>]
[<assembly: AssemblyInformationalVersionAttribute("1.2.5.*")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Groviera"
    let [<Literal>] AssemblyProduct = "Taipan"
    let [<Literal>] AssemblyCompany = "Enkomio"
    let [<Literal>] AssemblyDescription = "A web application vulnerability assessment tool."
    let [<Literal>] AssemblyVersion = "1.2.1202831766"
    let [<Literal>] AssemblyFileVersion = "1.2.1202831766"
    let [<Literal>] AssemblyInformationalVersion = "1.2.5.*"
