// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ES.Taipan.Application")>]
[<assembly: AssemblyProductAttribute("Taipan")>]
[<assembly: AssemblyCompanyAttribute("Enkomio")>]
[<assembly: AssemblyDescriptionAttribute("A web application vulnerability scanner tool.")>]
[<assembly: AssemblyVersionAttribute("0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("0.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.0.*")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ES.Taipan.Application"
    let [<Literal>] AssemblyProduct = "Taipan"
    let [<Literal>] AssemblyCompany = "Enkomio"
    let [<Literal>] AssemblyDescription = "A web application vulnerability scanner tool."
    let [<Literal>] AssemblyVersion = "0.0.0"
    let [<Literal>] AssemblyFileVersion = "0.0.0"
    let [<Literal>] AssemblyInformationalVersion = "0.0.0.*"
